name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'public/**'
jobs:
  check:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: check
    uses: ./.github/workflows/deploy.yml
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT_UNDERCARD_509BA}}

