name: Update images
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * 0
jobs:
  build:
    name: Update images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      pushed: ${{ steps.push.outputs.pushed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm clean-install
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ vars.TS_OAUTH_CLIENT_ID }}
          audience: ${{ vars.TS_AUDIENCE }}
          tags: tag:ci-proxy
      - name: Download images
        run: node scripts/downloadImages.js
        env:
          ALL_PROXY: socks5h://100.115.6.118:1080
      - name: Check for case collisions
        run: node scripts/checkCase.js
      - name: Commit and push
        id: push
        uses: ./.github/actions/commit-push
        with:
          message: Update images
  deploy:
    name: Trigger deploy
    needs: build
    if: needs.build.outputs.pushed == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy.yml
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT_UNDERCARD_509BA}}
